select * from data;

--Q1. What is the total revenue generated by male vs. female customers?
select 
gender , sum(purchase_amount) as total_revenue 
from data 
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select 
customer_id , purchase_amount 
from data 
where discount_applied = 'Yes' and  
      purchase_amount >= (
                        select avg(purchase_amount)
						from data);

-- Q3. Which are the top 5 products with the highest average review rating?
select 
item_purchased , 
ROUND(avg(review_rating)::NUMERIC , 2) as avg_rating
from data
group by item_purchased
order by avg_rating desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from data
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select 
subscription_status , 
round(avg(purchase_amount),2) as avg_purchase_amount , 
round(sum(purchase_amount),2) as total_purchase_amount 
from data
group by subscription_status
order by total_purchase_amount desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select 
item_purchased  , 
round(100.0 * sum(
                  case when discount_applied = 'Yes'
				  then 1
				  else 0
				  end
) / count(discount_applied) ,2) as discount_percentage
from data 
group by item_purchased
order by discount_percentage desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with segment as (
select customer_id , 
previous_purchases , 
case   when previous_purchases = 1 then 'new'
       when previous_purchases between 2 and 10 then 'Returning'
	   else 'loyal'
	   end as customer_category
from data 
)
select
customer_category ,
count(customer_category) as customer_category_count
from segment
group by customer_category;

--Q8. What are the top 3 most purchased products within each category? 
with category_data as (
select 
category , 
item_purchased , 
count(customer_id) as total_customers , 
row_number() over(
               partition by category 
			   order by count(customer_id) desc
			     ) as item_rank
from data
group by category , item_purchased
) 
select 
item_rank , category , 
item_purchased  , total_customers 
from category_data 
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
select 
age_group , 
sum(purchase_amount) as revenue_contribution
from data
group by age_group
order by revenue_contribution desc;